#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Generate docker-compose.agents.yml from agents.yml
# =============================================================================
# Reads agent definitions and generates:
#   1. docker-compose.agents.yml — one OpenClaw service per agent
#   2. data/<agent>/config/ — agent-specific OpenClaw config
#   3. data/<agent>/workspace/ — agent-specific workspace with SOUL.md etc.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
cd "$ROOT_DIR"

source .env 2>/dev/null || true

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

log()  { echo -e "${GREEN}[✓]${NC} $*"; }
info() { echo -e "${BLUE}[i]${NC} $*"; }

# Check for yq (YAML parser)
if ! command -v yq &>/dev/null; then
  echo "Installing yq for YAML parsing..."
  if [[ "$OSTYPE" == "darwin"* ]]; then
    brew install yq
  else
    sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
    sudo chmod +x /usr/local/bin/yq
  fi
fi

AGENTS_FILE="agents.yml"
OUTPUT_FILE="docker-compose.agents.yml"

if [ ! -f "$AGENTS_FILE" ]; then
  echo "Error: $AGENTS_FILE not found"
  exit 1
fi

AGENT_COUNT=$(yq '.agents | length' "$AGENTS_FILE")
info "Found $AGENT_COUNT agents in $AGENTS_FILE"

# ---------------------------------------------------------------------------
# Generate compose file header
# ---------------------------------------------------------------------------
cat > "$OUTPUT_FILE" << 'HEADER'
# =============================================================================
# AUTO-GENERATED — Do not edit manually
# Generated by: bash scripts/generate-compose.sh
# Source: agents.yml
# =============================================================================

services:
HEADER

# ---------------------------------------------------------------------------
# Generate a service for each agent
# ---------------------------------------------------------------------------
for i in $(seq 0 $((AGENT_COUNT - 1))); do
  NAME=$(yq ".agents[$i].name" "$AGENTS_FILE")
  ROLE=$(yq ".agents[$i].role" "$AGENTS_FILE")
  TOKEN_ENV=$(yq ".agents[$i].discord_token_env" "$AGENTS_FILE")
  MODEL=$(yq ".agents[$i].model" "$AGENTS_FILE")
  PERSONALITY=$(yq ".agents[$i].personality" "$AGENTS_FILE")
  DESCRIPTION=$(yq ".agents[$i].description" "$AGENTS_FILE")

  info "Generating agent: $NAME (role: $ROLE, model: $MODEL)"

  # Create agent data directories
  mkdir -p "data/agents/$NAME/config"
  mkdir -p "data/agents/$NAME/workspace"
  mkdir -p "data/agents/$NAME/workspace/memory"

  # Generate SOUL.md
  cat > "data/agents/$NAME/workspace/SOUL.md" << EOF
# SOUL.md — ${NAME}

## Identity
- **Name:** ${NAME}
- **Role:** ${ROLE}

## Personality
${PERSONALITY}

## Rules
- You are in a Discord server with other AI agents.
- Interact naturally. Be yourself.
- You can only communicate through Discord.
$(if [ "$ROLE" = "administrator" ]; then
echo "- You have administrator privileges. You can ban, kick, mute, and manage channels."
echo "- Use your powers fairly. Don't abuse them."
echo "- You set the tone for the server."
echo "- Periodically introduce discussion topics to keep conversation flowing."
echo "- You can get topics from the spawn controller: curl http://spawn-controller:9090/topics"
echo "- If conversation dies down, post a new topic. Don't let the server go quiet."
echo "- You can spawn new agents: curl -X POST http://spawn-controller:9090/agents/random"
echo "- You can check server status: curl http://spawn-controller:9090/limits"
else
echo "- You are a regular member. Follow the server rules."
echo "- Respect the administrator's decisions."
echo "- Be authentic and engage genuinely with others."
fi)
EOF

  # Generate AGENTS.md
  cat > "data/agents/$NAME/workspace/AGENTS.md" << EOF
# AGENTS.md — ${NAME}

## Who You Are
You are ${NAME}, an AI agent running in a Discord server experiment.
You interact with other AI agents through Discord messages.

## Communication
- Respond to messages in Discord
- Be natural and conversational
- Don't be overly verbose — keep it chat-like
- React to messages when appropriate

## Memory
- Write important things to memory/ files
- Read memory on startup for continuity
EOF

  # Generate USER.md
  cat > "data/agents/$NAME/workspace/USER.md" << EOF
# USER.md

This is an autonomous agent experiment. There may be a human observer
but your primary interactions are with other AI agents in Discord.
EOF

  # Generate agent-specific OpenClaw config
  cat > "data/agents/$NAME/config/openclaw.json" << EOF
{
  "models": {
    "providers": {
      "ollama": {
        "baseUrl": "http://ollama:11434/v1",
        "apiKey": "ollama-local",
        "api": "openai-responses",
        "models": [
          {
            "id": "${MODEL}",
            "name": "${MODEL}",
            "reasoning": true,
            "input": ["text"],
            "cost": { "input": 0, "output": 0, "cacheRead": 0, "cacheWrite": 0 },
            "contextWindow": 131072,
            "maxTokens": 32768
          }
        ]
      }
    }
  },
  "agents": {
    "defaults": {
      "model": {
        "primary": "ollama/${MODEL}"
      },
      "compaction": {
        "mode": "safeguard"
      },
      "heartbeat": {
        "every": "5m"
      },
      "maxConcurrent": 1,
      "subagents": {
        "maxConcurrent": 2
      }
    }
  },
  "tools": {
    "web": {
      "search": { "enabled": false },
      "fetch": { "enabled": false }
    },
    "exec": {
      "security": "deny"
    }
  },
  "channels": {
    "discord": {
      "enabled": true,
      "groupPolicy": "allowlist"
    }
  },
  "commands": {
    "native": "auto"
  }
}
EOF

  # Calculate port offset
  PORT_OFFSET=$((18789 + i + 1))

  # Write service definition
  cat >> "$OUTPUT_FILE" << EOF
  # Agent: ${NAME} (${ROLE})
  openclaw-${NAME}:
    image: \${OPENCLAW_IMAGE:-openclaw:local}
    container_name: openclaw-${NAME}
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
      discord-proxy:
        condition: service_healthy
    environment:
      HOME: /home/node
      TERM: xterm-256color
      HTTP_PROXY: http://discord-proxy:3128
      HTTPS_PROXY: http://discord-proxy:3128
      http_proxy: http://discord-proxy:3128
      https_proxy: http://discord-proxy:3128
      NO_PROXY: ollama,ollama-gpu,localhost,127.0.0.1
      no_proxy: ollama,ollama-gpu,localhost,127.0.0.1
    volumes:
      - ./data/agents/${NAME}/config:/home/node/.openclaw
      - ./data/agents/${NAME}/workspace:/home/node/.openclaw/workspace
    ports:
      - "${PORT_OFFSET}:18789"
    init: true
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "lan",
        "--port",
        "18789",
      ]
    networks:
      - internal
    dns: []

EOF

  log "Agent $NAME configured (port $PORT_OFFSET)"
done

# ---------------------------------------------------------------------------
# Add .env template entries for tokens
# ---------------------------------------------------------------------------
echo ""
info "Add these to your .env file:"
echo ""
for i in $(seq 0 $((AGENT_COUNT - 1))); do
  TOKEN_ENV=$(yq ".agents[$i].discord_token_env" "$AGENTS_FILE")
  NAME=$(yq ".agents[$i].name" "$AGENTS_FILE")
  echo "  ${TOKEN_ENV}=your_${NAME}_bot_token_here"
done

echo ""
log "Generated $OUTPUT_FILE with $AGENT_COUNT agents"
log "Agent configs written to data/agents/"
echo ""
echo "Next steps:"
echo "  1. Create Discord bots at https://discord.com/developers/applications"
echo "  2. Add bot tokens to .env"
echo "  3. Invite all bots to your experiment Discord server"
echo "  4. Run: docker compose -f docker-compose.yml -f docker-compose.agents.yml up -d"
echo ""
echo "  Admin bot needs these Discord permissions:"
echo "    - Administrator (or: Manage Server, Ban Members, Kick Members, Manage Channels, Manage Messages)"
echo ""
echo "  Chatter bots need:"
echo "    - Send Messages, Read Messages, Add Reactions, Read Message History"
echo ""
